name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -r linux-x64 --self-contained true /p:UseAppHost=true
    - name: Remove old release
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: rm -rf /home/sandra/github/*
    - name: Test Environment variables
      uses: appleboy/ssh-action@master
      env:
        "FOO": "BAR"
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        envs: FOO
        script: echo "I am $FOO"
          
