name: Release Main

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -r linux-x64 --self-contained true /p:UseAppHost=true
    - name: Test Environment variables
      uses: appleboy/ssh-action@master
      env:
        "TOKENST": ${{ secrets.BOTTOKENSTAGING }}
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        envs: TOKENST
        script: sed -i "'s/$Token_Staging/'"$TOKENST"'/g'" /home/sandra/github/publish/appsettings.json
          
